[build-system]
requires = ["setuptools==82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "telephuzz"
version = "0.1.0"
description = "A project for differential fuzzing of OpenAPI-based client libraries."
authors = [
    { name="Justin Steuer", email="s8jnsteu@stud.uni-saarland.de" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker==7.1.0",
    "mitmproxy==12.2.1",
    "requests==2.33.1",
    "PyYAML==6.0.3",
    "schemathesis==4.25.2"
]

[project.optional-dependencies]
dev = [
    "pytest==9.0.3",
    "ruff==0.15.10",
    "mypy==1.20.0",
    "types-docker==7.1.0.20260409",
    "pre-commit==4.5.1",
    "fastapi[standard]==0.136.1"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
telephuzz = ["py.typed"]

# -------------------------
# Ruff configuration
# -------------------------
[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
fixable = ["ALL"]
ignore = ["B008"] # complains about FastAPI Depends otherwise

[tool.ruff.lint.isort]
known-first-party = ["telephuzz"]